import { Course } from "./types";

export const courses: Course[] = [
  {
    id: "1",
    name: "React Basics",
    description: "Learn the basics of React.",
    price: 50,
    streamId: "stream123",
    creator: "John Doe",
    thumbnailUrl: "/images/react-basics.jpg",
  },
  {
    id: "2",
    name: "Advanced React",
    description: "Dive deeper into React with advanced concepts.",
    price: 75,
    streamId: "stream456",
    creator: "Jane Smith",
    thumbnailUrl: "/images/advanced-react.jpg",
  },
  {
    id: "3",
    name: "TypeScript for Beginners",
    description: "A beginner's guide to TypeScript.",
    price: 45,
    streamId: "stream789",
    creator: "Alice Johnson",
    thumbnailUrl: "/images/typescript-beginners.jpg",
  },
  {
    id: "4",
    name: "Node.js Fundamentals",
    description: "Learn the fundamentals of Node.js.",
    price: 60,
    streamId: "stream101",
    creator: "Bob Brown",
    thumbnailUrl: "/images/nodejs-fundamentals.jpg",
  },
  {
    id: "5",
    name: "Full-Stack Development",
    description: "Become a full-stack developer.",
    price: 100,
    streamId: "stream102",
    creator: "Charlie Davis",
    thumbnailUrl: "/images/full-stack-development.jpg",
  },
  {
    id: "6",
    name: "CSS Mastery",
    description: "Master the art of CSS.",
    price: 40,
    streamId: "stream103",
    creator: "Eve Clark",
    thumbnailUrl: "/images/css-mastery.jpg",
  },
];
